// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iuwzrpiipahkfcnknric.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1d3pycGlpcGFoa2ZjbmtucmljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NDA4MDcsImV4cCI6MjA2OTMxNjgwN30.3qUk_EmGqswGvLnKDWQQlFPGxiMMJtvM7CQxlxtLTc4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});